# This is a basic workflow to help you get started with Actions

name: Test Job

# Controls when the workflow will run
on: 
  workflow_dispatch:
    inputs:
      composer_install:
        type: boolean
        description: Execute composer install for the project?
        required: false
        default: 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Printing date in job 1
        run: |
          echo date
          echo ${{ github.event.inputs.composer_install }}
          echo ${{ github.event.inputs.composer_install == true }}
  job2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Printing date in job 2
        run: date
  job3:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Printing date in job 1
        run: date
  job4:
    runs-on: macos-latest
    needs: [job1,job2,job3]
    steps:
      - uses: actions/checkout@v2
      - name: Printing date in job 1
        run: date
      
